<?xml version="1.0" encoding="utf-8"?><Database Name="Tienda" Class="dcTiendaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-LN2ROB9J\SQLEXPRESS01;Initial Catalog=Tienda;Integrated Security=True" SettingsObjectName="JBTienda.Properties.Settings" SettingsPropertyName="TiendaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.agregarGerente" Method="agregarGerente">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="contraseña" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="apellidoPaterno" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="apellidoMaterno" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="idSexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="idTipoUsuario" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="idDepartamento" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.agregarProducto" Method="agregarProducto">
    <Parameter Name="nombreProducto" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="precio" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="cantidad" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="idDepartamento" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.cargarCiudades" Method="cargarCiudades">
    <Parameter Name="idEstado" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="cargarCiudadesResult">
      <Column Name="idCiudad" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="desCiudad" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="idEstado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.agregarUsuarios" Method="agregarUsuarios">
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="contraseña" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="contraseña2" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="apellidoPaterno" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="apellidoMaterno" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="idSexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(35)" />
    <Parameter Name="cp" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="idCiudad" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="idTipoUsuario" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CargarDescuentos" Method="CargarDescuentos">
    <ElementType Name="CargarDescuentosResult">
      <Column Name="idDescuento" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="descuento" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.cargarEstados" Method="cargarEstados">
    <ElementType Name="cargarEstadosResult">
      <Column Name="idEstado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="desEstado" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultarDep" Method="ConsultarDep">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(25)" />
    <ElementType Name="ConsultarDepResult">
      <Column Name="idDepartamento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarGerentes" Method="consultarGerentes">
    <ElementType Name="consultarGerentesResult">
      <Column Name="idGerente" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreCompleto" Type="System.String" DbType="VarChar(67)" CanBeNull="true" />
      <Column Name="nombredepa" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarUsuario" Method="consultarUsuario">
    <Parameter Name="idUsuario" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="consultarUsuarioResult">
      <Column Name="idUsuario" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="idSexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="cp" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="idCiudad" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="idTipoUsuario" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="idEstado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Logear" Method="Logear">
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="contraseña" Type="System.String" DbType="VarChar(25)" />
    <ElementType Name="LogearResult">
      <Column Name="idUsuario" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="idTipoUSuario" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LogearGerente" Method="LogearGerente">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="contraseña" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="LogearGerenteResult">
      <Column Name="idGerente" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="idTipoUsuario" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarProductos" Method="consultarProductos">
    <Parameter Name="idDepartamento" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="consultarProductosResult">
      <Column Name="idProducto" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombreDepa" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="nombreProducto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="idDescuento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarDatosProducto" Method="consultarDatosProducto">
    <ElementType Name="consultarDatosProductoResult">
      <Column Name="idProducto" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombreProducto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.modificarProducto" Method="modificarProducto">
    <Parameter Name="idProducto" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="nombreProduco" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantidad" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="idDescuento" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.consultarDatosProductos2" Method="consultarDatosProductos2">
    <Parameter Name="idProducto" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="consultarDatosProductos2Result">
      <Column Name="idProducto" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="nombreDepa" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="nombreProducto" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="idDescuento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.consultarGerente" Method="consultarGerente">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="consultarGerenteResult">
      <Column Name="NombreCompleto" Type="System.String" DbType="VarChar(67)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.eliminarProducto" Method="eliminarProducto">
    <Parameter Name="idProducto" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
</Database>